[project]
src = "src"

# now that you have this top-level named contract
# whenever you have a network without an address, it will use the moch address
# so be careful with top-level named contracts
# but it saves us extra lines if all goes well below
[networks.contracts.price_feed]
deployer_script = "script/deploy_mocks.py"
abi = "mock_v3_aggregator"

[networks.sepolia]
url = "$SEPOLIA_RPC_URL"
save_to_db = false
default_account_name = "sepoliatest"
explorer_uri = "https://eth-sepolia.blockscout.com/"
explorer_type = "blockscout"

[networks.sepolia.contracts.price_feed]
address = "0x694AA1769357215DE4FAC081bf1f309aDC325306"

[networks.anvil]
url = "http://127.0.0.1:8545"
chain_id = 31337
save_to_db = false
default_account_name = "anvil0"
prompt_live = false



# You can view all configuration options at https://cyfrin.github.io/moccasin/all_moccasin_toml_parameters.html
